### ISSUE TITLE
Add getBalance or something similar to check how much money a player has

### ISSUE THREAD

**Issue by CelticMinstrel** [fernferret/AllPay#11]
Pretty self-explanatory; you can check if they have enough money to pay a certain cost, but not get the exact amount of money they have.

**Comment by fernferret** [comment]
would you prefer: getBalance(Player p) or getBalance(String playerName)?

**Comment by CelticMinstrel** [comment]
I personally prefer passing player rather than player.getName().

**Comment by fernferret** [comment]
Roger, I think i'll make sure they're all done this way

**Comment by fernferret** [comment]
Done in 6b2b4c430d1730930d7e
