### ISSUE TITLE
EconXP support

### ISSUE THREAD

**Issue by SalieriC** [fernferret/AllPay#16]
Support for EconXP: http://dev.bukkit.org/server-mods/econxp/
I was invited to request for unsupported plugins here: https://github.com/Multiverse/Multiverse-Portals/issues/106
So here I am. I think EconXP is a nice and budding plugin wich is atm not so common but could be more attractive in the future.

**Comment by fernferret** [comment]
Awesome, I'll get support added soon. I have a few things to do with allpay before the next roll, but this will be included.

**Comment by SalieriC** [comment]
Thanks a lot.

**Comment by fernferret** [comment]
Uh not sure why you closed this issue... It's closed when it's done.

**Comment by fernferret** [comment]
Finished in 8af71470896ed9d3d8e76cbc692bd3379a020de6
