### ISSUE TITLE
Allow showReceipt() to be toggled

### ISSUE THREAD

**Issue by krinsdeath** [fernferret/AllPay#9]
Either through a flag (pay(player, type, amount, showreceipt)), or maybe a transaction class to create multiple payments and the commit them all through a batch process.

or not, dunno.

**Comment by fernferret** [comment]
Think i'll add another method, as you suggested. I don't really want to modify the existing API, ~~This will be done tonight~~.

EDIT: Apparently, my "tonight" was in valve time...

**Comment by fernferret** [comment]
Done in #15.
